update Makefile
Signed-off-by: Mayank Shah <mayank.shah@percona.com>

diff --git a/charts/everest/charts/everest-crds/Makefile b/charts/everest/charts/everest-crds/Makefile
--- a/charts/everest/charts/everest-crds/Makefile
+++ b/charts/everest/charts/everest-crds/Makefile
@@ -1,5 +1,11 @@
-VERSION ?= 0.0.0
 release:
+	@if [ -z "$(VERSION)" ]; then \
+		echo "Error: VERSION is not set."; \
+		exit 1; \
+	fi
 	@for crd in templates/*.yaml; do \
 		yq eval '.metadata.labels["helm.sh/chart-version"] = "$(VERSION)"' $$crd -i; \
 	done
+
+release-dev:
+	@$(MAKE) release VERSION=0.0.0
